[package]
name = "axum-server"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
publish = false

[dependencies]
axum = { version = "0.8", default-features = false, features = ["http1", "json", "tokio"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "net"] }

[profile.release]
codegen-units = 1
lto = "fat"
